# Servidor
server.port=8080

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=raizesdonordeste

# JWT
jwt.secret=raizesdonordeste2026chaveSecretaSuperSeguraParaJWT
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# App
spring.application.name=raizes-do-nordeste

springdoc.packagesToScan=com.raizesdonordeste.api.controller
springdoc.pathsToMatch=/**